name: Deployment

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - "backend/**"
      - "infra/**"

# Required for detect-changes
permissions:
  contents: read
  pull-requests: read

# Filter out which components has been changed
# and only deploy those with changes
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend-app: ${{ steps.filter.outputs.frontend-app }}
      frontend-landing: ${{ steps.filter.outputs.frontend-landing }}
      backend: ${{ steps.filter.outputs.backend }}
      infra: ${{ steps.filter.outputs.infra }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend-app:
              - 'frontend/sjekklista-app/**'
            frontend-landing:
              - 'frontend/sjekklista-landing/**'
            backend:
              - 'backend/**'
            infra:
              - 'infra/**'

  deploy-frontend-app:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend-app == 'true'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - run: npm ci && npm run build
        working-directory: frontend/sjekklista-app

      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "frontend/sjekklista-app"
          output_location: "dist"

  deploy-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: echo "Deploy backend here"

  deploy-infra:
    needs: detect-changes
    if: needs.detect-changes.outputs.infra == 'true'
    uses: ./.github/workflows/deploy-infra-template.yml
    with:
      environment: prod
