name: Deployment

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - "backend/**"
      - "infra/**"

# Required for detect-changes
permissions:
  contents: read
  pull-requests: read

# Filter out which components has been changed
# and only deploy those with changes
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend-app: ${{ steps.filter.outputs.frontend-app }}
      frontend-landing: ${{ steps.filter.outputs.frontend-landing }}
      backend: ${{ steps.filter.outputs.backend }}
      infra: ${{ steps.filter.outputs.infra }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend-app:
              - 'frontend/sjekklista-app/**'
            frontend-landing:
              - 'frontend/sjekklista-landing/**'
            backend:
              - 'backend/**'
            infra:
              - 'infra/**'

  deploy-frontend-app:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend-app == 'true'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/sjekklista-app/package-lock.json

      - run: npm ci && npm run build
        working-directory: frontend/sjekklista-app

      - uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "frontend/sjekklista-app"
          output_location: "dist"

  deploy-frontend-landing:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend-landing == 'true'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/sjekklista-landing/package-lock.json

      - run: npm ci && npm run build
        working-directory: frontend/sjekklista-landing

      - uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LANDING }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "frontend/sjekklista-landing"
          output_location: "dist"

  deploy-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: echo "Deploy backend here"

  deploy-infra:
    needs: detect-changes
    if: needs.detect-changes.outputs.infra == 'true'
    uses: ./.github/workflows/deploy-infra-template.yml
    with:
      environment: prod
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
