name: Pullrequest Testing

# Only run on PR into dev
on:
  pull_request:
    branches: [main]

# Required for detect-changes
permissions:
  contents: read
  pull-requests: read

# Filter out which components has been changes, and only test
# those with changes
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend-app: ${{ steps.filter.outputs.frontend-app }}
      frontend-landing: ${{ steps.filter.outputs.frontend-landing }}
      backend: ${{ steps.filter.outputs.backend }}
      infra: ${{ steps.filter.outputs.infra }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend-app:
              - 'frontend/sjekklista-app**'
            frontend-landing:
              - 'frontend/sjekklista-landing**'
            backend:
              - 'backend/**'
            infra:
              - 'infra/**'

  test-frontend-app:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend-app == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd frontend/sjekklista-app && npm ci && npm run test

  test-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Should test backend here.."
